### PR TITLE
V3.1.0

### PR DESCRIPTION
**Pull request by qwazwsx**
Relevant Issue: #9 

* added warning if you don't explicitly specify a schoolID and you are enrolled in multiple schools
* added param `schoolID` to `User.getCourses()` to specify which school to select

TODO: add param to documentation

### CODE REVIEW

**Comment by Lathryx** [comment]
It worked wonderfully! Well done @qwazwsx!

**Comment by qwazwsx** [comment]
Thanks for testing, this will be merged soon!

**Comment by Lathryx** [comment]
Okay, I can add the updated `grades` part of it as well.

**Comment by Lathryx** [comment]
I see I have been assigned, should I be able to edit the file? 🤔

**Comment by qwazwsx** [comment]
I think so? I'm not really too familiar with branches & PR's aswell. This is really my only ""large"" project I maintain that has other contributors. You might have to make a separate PR and I can merge them later.

**Comment by Lathryx** [comment]
Great! I'm happy to help! I've had a lot of fun figuring this out with you and getting some experience programming collaboratively! So thank you, as well! 

My Discord is *Lathryx#2826*, so hit me up when you're free! :)

**Pull request merged**
